import { ColorMap } from "../../constants/ColorMap";
import { BoxColors } from "../../types/types";

export const Bonus = () => {
  return (
    <span className="bonus">
      <svg stroke="#000" strokeLinecap="round" strokeLinejoin="round" strokeWidth={4}>
        <text
          stroke="#fff"
          strokeWidth={7}
          x="10px"
          y="50%"
          textAnchor="middle"
          dominantBaseline="central"
        >
          B
        </text>
        <text
          stroke="#fff"
          strokeWidth={7}
          x="24px"
          y="50%"
          textAnchor="middle"
          dominantBaseline="central"
        >
          O
        </text>
        <text
          stroke="#fff"
          strokeWidth={7}
          x="38px"
          y="50%"
          textAnchor="middle"
          dominantBaseline="central"
        >
          N
        </text>
        <text
          stroke="#fff"
          strokeWidth={7}
          x="52px"
          y="50%"
          textAnchor="middle"
          dominantBaseline="central"
        >
          U
        </text>
        <text
          stroke="#fff"
          strokeWidth={7}
          x="66px"
          y="50%"
          textAnchor="middle"
          dominantBaseline="central"
        >
          S
        </text>
        <text
          fill={ColorMap.get(BoxColors.Green)}
          x="10px"
          y="50%"
          textAnchor="middle"
          dominantBaseline="central"
        >
          B
        </text>
        <text
          fill={ColorMap.get(BoxColors.Yellow)}
          x="24px"
          y="50%"
          textAnchor="middle"
          dominantBaseline="central"
        >
          O
        </text>
        <text
          fill={ColorMap.get(BoxColors.Blue)}
          x="38px"
          y="50%"
          textAnchor="middle"
          dominantBaseline="central"
        >
          N
        </text>
        <text
          fill={ColorMap.get(BoxColors.Red)}
          x="52px"
          y="50%"
          textAnchor="middle"
          dominantBaseline="central"
        >
          U
        </text>
        <text
          fill={ColorMap.get(BoxColors.Orange)}
          x="66px"
          y="50%"
          textAnchor="middle"
          dominantBaseline="central"
        >
          S
        </text>
      </svg>
    </span>
  );
};
